# Generated by Django 3.2.4 on 2021-06-11 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
