# Generated by Django 3.2.4 on 2021-06-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='printing_status',
            field=models.BooleanField(default=False),
        ),
    ]
