# Generated by Django 3.2.4 on 2021-06-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='docfile',
            field=models.FileField(default='blank.pdf', upload_to='order_pdf'),
        ),
    ]
