# Generated by Django 3.2.4 on 2021-06-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_rename_pdf_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='docfile',
            field=models.FileField(default='blank.pdf', upload_to=''),
        ),
    ]
