# Generated by Django 3.2.4 on 2021-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_order_docfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='black_and_white',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ending_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='no_of_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='starting_page',
            field=models.IntegerField(default=1),
        ),
    ]
