# Generated by Django 3.2.4 on 2021-06-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20210614_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='black_and_white',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
