# Generated by Django 3.2.4 on 2021-06-16 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_order_black_and_white'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ending_page',
        ),
        migrations.RemoveField(
            model_name='order',
            name='starting_page',
        ),
    ]
