# Generated by Django 3.2.4 on 2021-06-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20210617_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_file_name',
            field=models.CharField(default='extra.pdf', max_length=100),
        ),
    ]
