# Generated by Django 3.2.4 on 2021-06-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_order_extra_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra_file_name',
        ),
    ]
