# Generated by Django 3.2.4 on 2021-06-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_remove_order_extra_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopkeeper_email',
            field=models.EmailField(default='shopkeeper@iitg.ac.in', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='shopkeeper_location',
            field=models.CharField(default='library', max_length=100),
        ),
    ]
